### PR TITLE
add customize border radius to botton

### PR DESCRIPTION
**Pull request by rezaghz**
Custom Border Radius is better !
thanks

### CODE REVIEW

**Comment by rezaghz** [comment]
add dispose animation controller

**Comment by chrisedg87** [comment]
Hi @rezaghz thanks for the PR! Where you intending the custom border radius just be applied to a button or the widget as a whole?

**Comment by rezaghz** [comment]
> Hi @rezaghz thanks for the PR! Where you intending the custom border radius just be applied to a button or the widget as a whole?

hi , just button applied

**Comment by chrisedg87** [comment]
Definitely need the dispose method but your changes to the border radius are currently only being applied to the checkmark animation. They'll need to be moved to the button radius to make this work. 

Happy to merge the dispose method if you want to submit that in a new pr.

**Pull request closed without merging**
